minimum_severity: MEDIUM

# In production, remove these and fix the issues
exclude:
  # Wide-open SSH is acceptable in lab because LocalStack
  # doesn't have real network exposure.
  - AVD-AWS-0107   # "An egress security group rule allows traffic to /0"
  - AVD-AWS-0104   # "Security group rule allows ingress from public internet"

format: default